/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eindexclient;

import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author catic
 */
public class ClientLoginGUI extends javax.swing.JFrame implements ServerHandler{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClientLoginGUI.class.getName());
    private final EIndexClient app;
    private final PrintWriter writer;

    /**
     * Creates new form ClientLoginGUI
     * @param app
     * @param writer
     */
    public ClientLoginGUI(EIndexClient app, PrintWriter writer) {
        this.app = app;
        this.writer = writer;
        initComponents();
    }
    
    @Override
    public void handleServerMessage(String message) {
        java.awt.EventQueue.invokeLater(() -> {
            if (message.startsWith("LOGIN_OK_ADMIN")) {
                JOptionPane.showMessageDialog(this, "Login successful as Admin!");
                app.switchToAdmin();       // switch GUI in main client
                this.dispose();             // close login window
            } else if (message.startsWith("LOGIN_OK_STUDENT")) {
                JOptionPane.showMessageDialog(this, "Login successful as Student!");
                app.switchToStudent(textFieldBoxUsername.getText().trim());      // switch GUI in main client
                this.dispose();
            } else if (message.startsWith("LOGIN_FAIL")) {
                JOptionPane.showMessageDialog(this, "Login failed: " + message.split(" ", 2)[1]);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonLogin = new javax.swing.JButton();
        labelRole = new javax.swing.JLabel();
        comboBoxAdminRole = new javax.swing.JComboBox<>();
        labelEIndexLoginPanelTitle = new javax.swing.JLabel();
        textFieldBoxPassword = new javax.swing.JPasswordField();
        textFieldBoxUsername = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonLogin.setText("Log in");
        buttonLogin.setAutoscrolls(true);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        labelRole.setText("Role");
        labelRole.setAutoscrolls(true);

        comboBoxAdminRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Student" }));
        comboBoxAdminRole.setAutoscrolls(true);
        comboBoxAdminRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAdminRoleActionPerformed(evt);
            }
        });

        labelEIndexLoginPanelTitle.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        labelEIndexLoginPanelTitle.setText("EIndex Login Panel");

        textFieldBoxPassword.setText("ADMIN");
        textFieldBoxPassword.setMinimumSize(new java.awt.Dimension(200, 25));
        textFieldBoxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBoxPasswordActionPerformed(evt);
            }
        });

        textFieldBoxUsername.setText("ADMIN");
        textFieldBoxUsername.setPreferredSize(new java.awt.Dimension(200, 25));
        textFieldBoxUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBoxUsernameActionPerformed(evt);
            }
        });

        labelPassword.setText("Password");
        labelPassword.setAutoscrolls(true);

        labelUsername.setText("Username");
        labelUsername.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(labelEIndexLoginPanelTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelPassword)
                                        .addComponent(labelRole))
                                    .addComponent(labelUsername))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxAdminRole, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textFieldBoxPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldBoxUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(buttonLogin)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelEIndexLoginPanelTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBoxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textFieldBoxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxAdminRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRole))
                .addGap(31, 31, 31)
                .addComponent(buttonLogin)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        String username = textFieldBoxUsername.getText().trim();
        String password = new String(textFieldBoxPassword.getPassword());
        String role = comboBoxAdminRole.getSelectedItem().toString().toLowerCase();

        // Simple validation
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter both username and password!");
            return;
        }

        // Send login request to server
        writer.println("LOGIN:" + role + ":" + username + ":" + password);
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void comboBoxAdminRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAdminRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxAdminRoleActionPerformed

    private void textFieldBoxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBoxPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBoxPasswordActionPerformed

    private void textFieldBoxUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBoxUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBoxUsernameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JComboBox<String> comboBoxAdminRole;
    private javax.swing.JLabel labelEIndexLoginPanelTitle;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPasswordField textFieldBoxPassword;
    private javax.swing.JTextField textFieldBoxUsername;
    // End of variables declaration//GEN-END:variables
}
